version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: adlab-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=${DB_PATH}
      - ATTACK_RUNNER_URL=${ATTACK_RUNNER_URL}
      - ATTACK_RUNNER_TOKEN=${ATTACK_RUNNER_TOKEN}
      - EVENT_SAVE_MODE=${EVENT_SAVE_MODE}
      - BACKEND_IP=${BACKEND_IP}
    networks:
      - adlab-net

  collector:
    build: ./collector
    container_name: adlab-collector
    ports:
      - "5044:5044"   # Winlogbeat -> Logstash
    volumes:
      - ./collector/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - backend
    networks:
      - adlab-net

  mcp:
      build:
        context: ./mcp
        dockerfile: Dockerfile
      container_name: adlab-mcp
      ports:
        - "9000:9000"
      volumes:
        - ./data:/data
      environment:
        - BACKEND_URL=http://backend:8000
        - DB_PATH=/data/events.db
        - MCP_TRANSPORT=http
        - ATTACK_RUNNER_URL=${ATTACK_RUNNER_URL}
        - ATTACK_RUNNER_TOKEN=${ATTACK_RUNNER_TOKEN}
        - VICTIM_URL=${VICTIM_URL}
        - ATTACK_REQUESTED_BY=${ATTACK_REQUESTED_BY}
      depends_on:
        - backend
      networks:
        - adlab-net
      restart: unless-stopped



  dashboard:
    build: ./dashboard
    container_name: adlab-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/data
    depends_on:
      - backend
      - mcp
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:8000
      # - ATTACK_REQUESTED_BY=${ATTACK_REQUESTED_BY}
      # - VICTIM_URL=${VICTIM_URL}
      - MCP_URL=http://mcp:9000/mcp
    networks:
      - adlab-net

networks:
  adlab-net:
    driver: bridge