version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: adlab-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - DB_PATH=${DB_PATH}
      - ATTACK_RUNNER_URL=${ATTACK_RUNNER_URL}
      - ATTACK_RUNNER_TOKEN=${ATTACK_RUNNER_TOKEN}
    networks:
      - adlab-net

  collector:
    build: ./collector
    container_name: adlab-collector
    ports:
      - "5044:5044"   # Winlogbeat -> Logstash
    volumes:
      - ./collector/pipeline:/usr/share/logstash/pipeline
    depends_on:
      - backend
    networks:
      - adlab-net

  dashboard:
    build: ./dashboard
    container_name: adlab-dashboard
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
      - ATTACK_REQUESTED_BY=${ATTACK_REQUESTED_BY}
      - VICTIM_URL=${VICTIM_URL}
    networks:
      - adlab-net

networks:
  adlab-net:
    driver: bridge